config/routes.rb
Rails.application.routes.draw do
  resources :classroom_teachers
  resources :classroom_students
  resources :classrooms
  resources :items
  resources :type_items
  resources :people
  resources :teachers
  resources :students
  resources :subjects
  resources :tasks
  get 'pages/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/classroom.rb
class Classroom < ApplicationRecord
end

app/models/classroom_student.rb
class ClassroomStudent < ApplicationRecord
  belongs_to :classroom
  belongs_to :student
end

app/models/classroom_teacher.rb
class ClassroomTeacher < ApplicationRecord
  belongs_to :classroom
  belongs_to :teacher
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :type_item
end

app/models/person.rb
class Person < ApplicationRecord
    has_one :teacher 
    has_one :student
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :person
  has_many :classrooms
end

app/models/subject.rb
class Subject < ApplicationRecord
end

app/models/task.rb
class Task < ApplicationRecord
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  belongs_to :person
  has_many :classrooms_teachers
end

app/models/type_item.rb
class TypeItem < ApplicationRecord
    has_many :items
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: %i[ show edit update destroy ]

  # GET /items or /items.json
  def index
    @items = Item.all
  end

  # GET /items/1 or /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items or /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to item_url(@item), notice: "Item was successfully created." }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1 or /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to item_url(@item), notice: "Item was successfully updated." }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1 or /items/1.json
  def destroy
    @item.destroy

    respond_to do |format|
      format.html { redirect_to items_url, notice: "Item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def item_params
      params.require(:item).permit(:name, :active, :type_item_id)
    end
end

app/controllers/type_items_controller.rb
class TypeItemsController < ApplicationController
  before_action :set_type_item, only: %i[ show edit update destroy ]

  # GET /type_items or /type_items.json
  def index
    @type_items = TypeItem.all
  end

  # GET /type_items/1 or /type_items/1.json
  def show
  end

  # GET /type_items/new
  def new
    @type_item = TypeItem.new
  end

  # GET /type_items/1/edit
  def edit
  end

  # POST /type_items or /type_items.json
  def create
    @type_item = TypeItem.new(type_item_params)

    respond_to do |format|
      if @type_item.save
        format.html { redirect_to type_item_url(@type_item), notice: "Type item was successfully created." }
        format.json { render :show, status: :created, location: @type_item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @type_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /type_items/1 or /type_items/1.json
  def update
    respond_to do |format|
      if @type_item.update(type_item_params)
        format.html { redirect_to type_item_url(@type_item), notice: "Type item was successfully updated." }
        format.json { render :show, status: :ok, location: @type_item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @type_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /type_items/1 or /type_items/1.json
  def destroy
    @type_item.destroy

    respond_to do |format|
      format.html { redirect_to type_items_url, notice: "Type item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_type_item
      @type_item = TypeItem.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def type_item_params
      params.require(:type_item).permit(:name, :active)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/type_items_helper.rb
module TypeItemsHelper
end

app/views/type_items/_form.html.erb
<%= form_with(model: type_item) do |form| %>
  <% if type_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(type_item.errors.count, "error") %> prohibited this type_item from being saved:</h2>

      <ul>
        <% type_item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group mb-3">
    <%= form.label :name, class: "form-label" %>
    <%= form.text_field :name, class:"form-control" %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :active, class: "form-check-label" %>
    <%= form.check_box :active, class:"form-check-input" %>
  </div>

  <div class="form-group mb-3">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/type_items/_type_item.html.erb
<div id="<%= dom_id type_item %>">
  <p>
    <strong>Name:</strong>
    <%= type_item.name %>
  </p>

  <p>
    <strong>Active:</strong>
    <%= type_item.active %>
  </p>

</div>

app/views/type_items/edit.html.erb
<div class="container-fluid">
  <h1>Editing Type Item</h1>

  <%= render 'form', type_item: @type_item %>

  <%= link_to 'Show', @type_item, class: "btn btn-light min-width-btn" %> |
  <%= link_to 'Back', type_items_path, class: "btn btn-light min-width-btn" %>
</div>

app/views/type_items/index.html.erb
<div class="container-fluid">
  <p id="notice"><%= notice %></p>

  <h1>Type Items</h1>

  <table class="table">
    <thead>
      <tr>
          <th>Name</th>
          <th>Active</th>
          <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @type_items.each do |type_item| %>
        <tr>
            <td><%= type_item.name %></td>
            <td><%= type_item.active %></td>
            <td><%= link_to 'Show', type_item %></td>
          <td><%= link_to 'Edit', edit_type_item_path(type_item) %></td>
          <td><%= link_to 'Destroy', type_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Type Item', new_type_item_path, class: "btn btn-success min-width-btn" %>

</div>

app/views/type_items/new.html.erb
<div class="container-fluid">
  <h1>New Type Item</h1>

  <%= render 'form', type_item: @type_item %>

  <%= link_to 'Back', type_items_path, class: "btn btn-light min-width-btn" %>
</div>

app/views/type_items/show.html.erb
<div class="container-fluid">
  <p id="notice"><%= notice %></p>

      <div class="form-group mb-3">
    <p><strong>Name:</strong></p>
    <div>
      <%= @type_item.name %>
    </div>
  </div>
  
      <div class="form-group mb-3">
    <p><strong>Active:</strong></p>
    <div>
      <%= @type_item.active %>
    </div>
  </div>
  
  
  <%= link_to 'Edit', edit_type_item_path(@type_item), class: "btn btn-primary min-width-btn" %>
  <%= link_to 'Back', type_items_path, class: "btn btn-light min-width-btn" %>
</div>