config/routes.rb
Rails.application.routes.draw do
  resources :classroom_teachers
  resources :classroom_students
  resources :classrooms
  resources :items
  resources :type_items
  resources :people
  resources :teachers
  resources :students
  resources :subjects
  resources :tasks
  get 'pages/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/classroom.rb
class Classroom < ApplicationRecord
end

app/models/classroom_student.rb
class ClassroomStudent < ApplicationRecord
  belongs_to :classroom
  belongs_to :student
end

app/models/classroom_teacher.rb
class ClassroomTeacher < ApplicationRecord
  belongs_to :classroom
  belongs_to :teacher
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :type_item
end

app/models/person.rb
class Person < ApplicationRecord
    has_one :teacher 
    has_one :student
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :person
  has_many :classrooms
end

app/models/subject.rb
class Subject < ApplicationRecord
end

app/models/task.rb
class Task < ApplicationRecord
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  belongs_to :person
  has_many :classrooms_teachers
end

app/models/type_item.rb
class TypeItem < ApplicationRecord
    has_many :items
end

app/controllers/classroom_teachers_controller.rb
class ClassroomTeachersController < ApplicationController
  before_action :set_classroom_teacher, only: %i[ show edit update destroy ]

  # GET /classroom_teachers or /classroom_teachers.json
  def index
    @classroom_teachers = ClassroomTeacher.all
  end

  # GET /classroom_teachers/1 or /classroom_teachers/1.json
  def show
  end

  # GET /classroom_teachers/new
  def new
    @classroom_teacher = ClassroomTeacher.new
  end

  # GET /classroom_teachers/1/edit
  def edit
  end

  # POST /classroom_teachers or /classroom_teachers.json
  def create
    @classroom_teacher = ClassroomTeacher.new(classroom_teacher_params)

    respond_to do |format|
      if @classroom_teacher.save
        format.html { redirect_to classroom_teacher_url(@classroom_teacher), notice: "Classroom teacher was successfully created." }
        format.json { render :show, status: :created, location: @classroom_teacher }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @classroom_teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /classroom_teachers/1 or /classroom_teachers/1.json
  def update
    respond_to do |format|
      if @classroom_teacher.update(classroom_teacher_params)
        format.html { redirect_to classroom_teacher_url(@classroom_teacher), notice: "Classroom teacher was successfully updated." }
        format.json { render :show, status: :ok, location: @classroom_teacher }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @classroom_teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /classroom_teachers/1 or /classroom_teachers/1.json
  def destroy
    @classroom_teacher.destroy

    respond_to do |format|
      format.html { redirect_to classroom_teachers_url, notice: "Classroom teacher was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_classroom_teacher
      @classroom_teacher = ClassroomTeacher.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def classroom_teacher_params
      params.require(:classroom_teacher).permit(:classroom_id, :teacher_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/classroom_teachers_helper.rb
module ClassroomTeachersHelper
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/type_items_helper.rb
module TypeItemsHelper
end

app/views/classroom_teachers/_classroom_teacher.html.erb
<div id="<%= dom_id classroom_teacher %>">
  <p>
    <strong>Classroom:</strong>
    <%= classroom_teacher.classroom_id %>
  </p>

  <p>
    <strong>Teacher:</strong>
    <%= classroom_teacher.teacher_id %>
  </p>

</div>

app/views/classroom_teachers/_form.html.erb
<%= form_with(model: classroom_teacher) do |form| %>
  <% if classroom_teacher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(classroom_teacher.errors.count, "error") %> prohibited this classroom_teacher from being saved:</h2>

      <ul>
        <% classroom_teacher.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group mb-3">
    <%= form.label :classroom_id %>
    <%= form.collection_select :classroom_id, Classroom.all, :id, :name, { prompt: true }, { class: "form-select" }  %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :teacher_id %>
    <%= form.collection_select :teacher_id, Teacher.all, :id, :name, { prompt: true }, { class: "form-select" }  %>
  </div>

  <div class="form-group mb-3">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/classroom_teachers/edit.html.erb
<div class="container-fluid">
  <h1>Editing Classroom Teacher</h1>

  <%= render 'form', classroom_teacher: @classroom_teacher %>

  <%= link_to 'Show', @classroom_teacher, class: "btn btn-light min-width-btn" %> |
  <%= link_to 'Back', classroom_teachers_path, class: "btn btn-light min-width-btn" %>
</div>

app/views/classroom_teachers/index.html.erb
<div class="container-fluid">
  <p id="notice"><%= notice %></p>

  <h1>Classroom Teachers</h1>

  <table class="table">
    <thead>
      <tr>
          <th>Classroom</th>
          <th>Teacher</th>
          <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @classroom_teachers.each do |classroom_teacher| %>
        <tr>
            <td><%= classroom_teacher.classroom_id %></td>
            <td><%= classroom_teacher.teacher_id %></td>
            <td><%= link_to 'Show', classroom_teacher %></td>
          <td><%= link_to 'Edit', edit_classroom_teacher_path(classroom_teacher) %></td>
          <td><%= link_to 'Destroy', classroom_teacher, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Classroom Teacher', new_classroom_teacher_path, class: "btn btn-success min-width-btn" %>

</div>

app/views/classroom_teachers/new.html.erb
<div class="container-fluid">
  <h1>New Classroom Teacher</h1>

  <%= render 'form', classroom_teacher: @classroom_teacher %>

  <%= link_to 'Back', classroom_teachers_path, class: "btn btn-light min-width-btn" %>
</div>

app/views/classroom_teachers/show.html.erb
<div class="container-fluid">
  <p id="notice"><%= notice %></p>

      <div class="form-group mb-3">
    <p><strong>Classroom:</strong></p>
    <div>
      <%= @classroom_teacher.classroom_id %>
    </div>
  </div>
  
      <div class="form-group mb-3">
    <p><strong>Teacher:</strong></p>
    <div>
      <%= @classroom_teacher.teacher_id %>
    </div>
  </div>
  
  
  <%= link_to 'Edit', edit_classroom_teacher_path(@classroom_teacher), class: "btn btn-primary min-width-btn" %>
  <%= link_to 'Back', classroom_teachers_path, class: "btn btn-light min-width-btn" %>
</div>