config/routes.rb
Rails.application.routes.draw do
  resources :classroom_teachers
  resources :classroom_students
  resources :classrooms
  resources :items
  resources :type_items
  resources :people
  resources :teachers
  resources :students
  resources :subjects
  resources :tasks
  get 'pages/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/classroom.rb
class Classroom < ApplicationRecord
end

app/models/classroom_student.rb
class ClassroomStudent < ApplicationRecord
  belongs_to :classroom
  belongs_to :student
end

app/models/classroom_teacher.rb
class ClassroomTeacher < ApplicationRecord
  belongs_to :classroom
  belongs_to :teacher
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :type_item
end

app/models/person.rb
class Person < ApplicationRecord
    has_one :teacher 
    has_one :student
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :person
  has_many :classrooms
end

app/models/subject.rb
class Subject < ApplicationRecord
end

app/models/task.rb
class Task < ApplicationRecord
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  belongs_to :person
  has_many :classrooms_teachers
end

app/models/type_item.rb
class TypeItem < ApplicationRecord
    has_many :items
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: %i[ show edit update destroy ]

  # GET /items or /items.json
  def index
    @items = Item.all
  end

  # GET /items/1 or /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items or /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to item_url(@item), notice: "Item was successfully created." }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1 or /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to item_url(@item), notice: "Item was successfully updated." }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1 or /items/1.json
  def destroy
    @item.destroy

    respond_to do |format|
      format.html { redirect_to items_url, notice: "Item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def item_params
      params.require(:item).permit(:name, :active, :type_item_id)
    end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :set_teacher, only: %i[ show edit update destroy ]

  # GET /teachers or /teachers.json
  def index
    @teachers = Teacher.all
  end

  # GET /teachers/1 or /teachers/1.json
  def show
  end

  # GET /teachers/new
  def new
    @teacher = Teacher.new
  end

  # GET /teachers/1/edit
  def edit
  end

  # POST /teachers or /teachers.json
  def create
    @teacher = Teacher.new(teacher_params)

    respond_to do |format|
      if @teacher.save
        format.html { redirect_to teacher_url(@teacher), notice: "Teacher was successfully created." }
        format.json { render :show, status: :created, location: @teacher }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teachers/1 or /teachers/1.json
  def update
    respond_to do |format|
      if @teacher.update(teacher_params)
        format.html { redirect_to teacher_url(@teacher), notice: "Teacher was successfully updated." }
        format.json { render :show, status: :ok, location: @teacher }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teachers/1 or /teachers/1.json
  def destroy
    @teacher.destroy

    respond_to do |format|
      format.html { redirect_to teachers_url, notice: "Teacher was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teacher
      @teacher = Teacher.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def teacher_params
      params.require(:teacher).permit(:person_id, :graduation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/type_items_helper.rb
module TypeItemsHelper
end

app/views/teachers/_form.html.erb
<%= form_with(model: teacher) do |form| %>
  <% if teacher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(teacher.errors.count, "error") %> prohibited this teacher from being saved:</h2>

      <ul>
        <% teacher.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group mb-3">
    <%= form.label :person_id %>
    <%= form.collection_select :person_id, Person.all, :id, :name, { prompt: true }, { class: "form-select" }  %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :graduation, class: "form-label" %>
    <%= form.text_field :graduation, class:"form-control" %>
  </div>

  <div class="form-group mb-3">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/teachers/_teacher.html.erb
<div id="<%= dom_id teacher %>">
  <p>
    <strong>Person:</strong>
    <%= teacher.person_id %>
  </p>

  <p>
    <strong>Graduation:</strong>
    <%= teacher.graduation %>
  </p>

</div>

app/views/teachers/edit.html.erb
<div class="container-fluid">
  <h1>Editing Teacher</h1>

  <%= render 'form', teacher: @teacher %>

  <%= link_to 'Show', @teacher, class: "btn btn-light min-width-btn" %> |
  <%= link_to 'Back', teachers_path, class: "btn btn-light min-width-btn" %>
</div>

app/views/teachers/index.html.erb
<div class="container-fluid">
  <p id="notice"><%= notice %></p>

  <h1>Teachers</h1>

  <table class="table">
    <thead>
      <tr>
          <th>Person</th>
          <th>Graduation</th>
          <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @teachers.each do |teacher| %>
        <tr>
            <td><%= teacher.person_id %></td>
            <td><%= teacher.graduation %></td>
            <td><%= link_to 'Show', teacher %></td>
          <td><%= link_to 'Edit', edit_teacher_path(teacher) %></td>
          <td><%= link_to 'Destroy', teacher, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Teacher', new_teacher_path, class: "btn btn-success min-width-btn" %>

</div>

app/views/teachers/new.html.erb
<div class="container-fluid">
  <h1>New Teacher</h1>

  <%= render 'form', teacher: @teacher %>

  <%= link_to 'Back', teachers_path, class: "btn btn-light min-width-btn" %>
</div>

app/views/teachers/show.html.erb
<div class="container-fluid">
  <p id="notice"><%= notice %></p>

      <div class="form-group mb-3">
    <p><strong>Person:</strong></p>
    <div>
      <%= @teacher.person_id %>
    </div>
  </div>
  
      <div class="form-group mb-3">
    <p><strong>Graduation:</strong></p>
    <div>
      <%= @teacher.graduation %>
    </div>
  </div>
  
  
  <%= link_to 'Edit', edit_teacher_path(@teacher), class: "btn btn-primary min-width-btn" %>
  <%= link_to 'Back', teachers_path, class: "btn btn-light min-width-btn" %>
</div>